apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cloudprober.fullname" . }}-config
  labels:
    {{- include "cloudprober.labels" . | nindent 4 }}
data:
  cloudprober.cfg: |
    probe {
      name: "metrics-app.host"
      type: HTTP
      targets {
        host_names: "{{ .Values.targetHost }}"
      }

      http_probe {
        protocol: HTTP
        headers {
          name: "Host"
          value: "metrics-app.host"
        }
      }
      interval_msec:   1  # .001s
      timeout_msec:   50  # .05s
    }

    probe {
      name: "metrics-app.host/err"
      type: HTTP
      targets {
        host_names: "{{ .Values.targetHost }}"
      }

      http_probe {
        protocol: HTTP
        relative_url: "/err"
        headers {
          name: "Host"
          value: "metrics-app.host"
        }
      }
      interval_msec:   3  # .001s
      timeout_msec:   50  # .05s
    }

    probe {
      name: "slo-app.host"
      type: HTTP
      targets {
        host_names: "{{ .Values.targetHost }}"
      }

      http_probe {
        protocol: HTTP
        headers {
          name: "Host"
          value: "slo-app.host"
        }
      }
      interval_msec:   1  # .001s
      timeout_msec:   50  # .05s
    }
