{
 "title": "Cloudprober",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Average Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "rate(latency[5m])/rate(total[5m])",
     "legendFormat": "{{probe}}"
    }
   ]
  },
  {
   "title": "Requests (per sec)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(total[5m])", "legendFormat": "{{probe}}" }
   ]
  },
  {
   "title": "Requests by Code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(resp_code[5m])", "legendFormat": "{{probe}} - {{code}}" }
   ]
  },
  {
   "title": "Timeouts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(timeouts[5m])", "legendFormat": "{{probe}}" }
   ]
  }
 ]
}